[package]
name = "gluon"
version = "0.0.1"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^1.0.31"
handlebars = "^3.1.0"
serde = { version = "^1.0.111", features = ["derive"] }
structopt = "^0.3.14"
thiserror = "^1.0.19"
