[package]
name = "operator"
version = "0.6.1"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
description = "A web server for static and dynamic content"
repository = "https://github.com/mkantor/operator"
homepage = "https://operator.mattkantor.com"
categories = [
    "web-programming::http-server",
    "command-line-utilities",
]
keywords = [
    "web",
    "server",
    "http",
    "templating",
    "handlebars",
]
readme = "README.md"
license = "GPL-3.0"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",

    # Ideally this would not be necessary, but when `cargo publish` verifies
    # the package tarball it checks [[bench]] and fails without this.
    "benches/**/*",
]

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.3"
anyhow = "1.0.62"
bytes = "0.5.6"
futures = "0.3.23"
handlebars = "4.3.3"
log = "0.4.17"
mime = "0.3.16"
mime_guess = "2.0.4"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
stderrlog = "0.5.3"
structopt = "0.3.26"
thiserror = "1.0.32"
walkdir = "2.3.2"

[dev-dependencies]
criterion = "0.3.6"
env_logger = "0.9.0"
insta = { version = "1.18.2", features = ["yaml"] }
lazy_static = "1.4.0"
maplit = "1.0.2"
regex = "1.6.0"
tempfile = "3.3.0"
test-log = "0.2.11"

[[bench]]
name = "load_test"
harness = false
