[package]
name = "soliton"
version = "0.0.1"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
description = "A content framework for websites"
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.0.0-beta.1"
anyhow = "1.0.31"
bytes = "0.5.6"
futures = "0.3.5"
handlebars = "3.3.0"
log = "0.4.11"
mime = "0.3.16"
mime_guess = "2.0.3"
serde = { version = "1.0.114", features = ["derive"] }
stderrlog = "0.4.3"
structopt = "0.3.15"
thiserror = "1.0.20"
walkdir = "2.3.1"

[dev-dependencies]
futures = "0.3.5"
insta = "0.16.1"
maplit = "1.0.2"
regex = "1.3.9"
serde_json = "1.0.57"
tempfile = "3.1.0"
