[package]
name = "operator"
version = "0.1.1"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
description = "A web server for static and dynamic content"
repository = "https://github.com/mkantor/operator"
homepage = "https://operator.mattkantor.com"
categories = [
    "web-programming::http-server",
    "command-line-utilities",
]
keywords = [
    "web",
    "server",
    "http",
    "templating",
    "handlebars",
]
readme = "README.md"
license = "GPL-3.0"
edition = "2018"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",

    # Ideally this would not be necessary, but when `cargo publish` verifies
    # the package tarball it checks [[bench]] and fails without this.
    "benches/**/*",
]

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.0"
anyhow = "1.0.34"
bytes = "0.5.6"
futures = "0.3.8"
handlebars = "3.5.1"
log = "0.4.11"
mime = "0.3.16"
mime_guess = "2.0.3"
serde = { version = "1.0.117", features = ["derive"] }
stderrlog = "0.5.0"
structopt = "0.3.20"
thiserror = "1.0.22"
walkdir = "2.3.1"

[dev-dependencies]
criterion = "0.3.3"
env_logger = "0.8.2"
insta = "1.3.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
regex = "1.4.2"
serde_json = "1.0.59"
tempfile = "3.1.0"
test-env-log = "0.2.2"

[[bench]]
name = "load_test"
harness = false
