[package]
name = "operator"
version = "0.2.0"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
description = "A web server for static and dynamic content"
repository = "https://github.com/mkantor/operator"
homepage = "https://operator.mattkantor.com"
categories = [
    "web-programming::http-server",
    "command-line-utilities",
]
keywords = [
    "web",
    "server",
    "http",
    "templating",
    "handlebars",
]
readme = "README.md"
license = "GPL-3.0"
edition = "2018"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",

    # Ideally this would not be necessary, but when `cargo publish` verifies
    # the package tarball it checks [[bench]] and fails without this.
    "benches/**/*",
]

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
anyhow = "1.0.41"
bytes = "0.5.6"
futures = "0.3.15"
handlebars = "4.0.0"
log = "0.4.14"
mime = "0.3.16"
mime_guess = "2.0.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
stderrlog = "0.5.1"
structopt = "0.3.21"
thiserror = "1.0.25"
walkdir = "2.3.2"

[dev-dependencies]
criterion = "0.3.4"
env_logger = "0.8.4"
insta = "1.7.1"
lazy_static = "1.4.0"
maplit = "1.0.2"
regex = "1.5.4"
tempfile = "3.2.0"
test-env-log = "0.2.7"

[[bench]]
name = "load_test"
harness = false
