[package]
name = "operator"
version = "0.0.2"
authors = ["Matt Kantor <the.matt.kantor@gmail.com>"]
description = "A web server for static and dynamic content"
repository = "https://github.com/mkantor/operator"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"
exclude = [
    "samples",
    "tests",
]

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.1.0"
anyhow = "1.0.33"
bytes = "0.5.6"
futures = "0.3.6"
handlebars = "3.5.0"
log = "0.4.11"
mime = "0.3.16"
mime_guess = "2.0.3"
serde = { version = "1.0.116", features = ["derive"] }
stderrlog = "0.5.0"
structopt = "0.3.18"
thiserror = "1.0.21"
walkdir = "2.3.1"

[dev-dependencies]
env_logger = "0.7.1"
insta = "1.0.0"
maplit = "1.0.2"
regex = "1.3.9"
serde_json = "1.0.58"
tempfile = "3.1.0"
test-env-log = "0.2.2"
