name: validate commit

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  debug-target:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
        include:
          - os: macos-latest
            artifact_prefix: macos-x86-64
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          key: release-${{ runner.os }}-${{ github.job }}-${{ secrets.CI_CACHE_VERSION }}
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
